[platformio]
default_envs = esp32
extra_configs = credentials.ini
# Select what example to compile uncommenting only ONE of this lines:

# Use this for CALE.es
# 1 BIT mono: Works as expected
#src_dir = examples/CALE
# 3 BIT grayscale: Still does not work correctly
#src_dir = examples/CALE-grayscale

# NEW ones from last Inkplate update:




[env:esp32]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
monitor_speed = 115200
board = esp32dev
; CPU Frequency. Max for ESP32: 240000000L
board_build.f_cpu = 240000000L

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
   

    
lib_deps=
   https://github.com/adafruit/Adafruit_Sensor.git
   https://github.com/e-radionicacom/Inkplate-6-Arduino-library.git
   https://github.com/e-radionicacom/Inkplate-6-SDFat-Arduino-Library.git
   https://github.com/adafruit/Adafruit_BME680.git
   https://github.com/adafruit/Adafruit_BusIO
   bblanchon/ArduinoJson@^7.0.4
   links2004/WebSockets @ ^2.7.3
   adafruit/Adafruit GFX Library @ ^1.12.4
